# COLT config file
--- !ionization               # MCRT ionization equilibrium module

init_dir: ics                 # Initial conditions directory (default: "ics")
init_base: colt               # Initial conditions base name (optional)
output_dir: output            # Output directory name (default: "output")
output_base: ion-eq-pre8      # Output file base name (default: "colt")
# abundances_base: states       # Output a separate abundances file
abundances_base: states-teq   # Output a separate abundances file

# Information about sources
source_file_Z_age: /home/arsmith/colt/tables/bpass-spectra-bin-imf_chab100.hdf5
# dust_model: /home/arsmith/colt/tables/Draine-SMC.hdf5
dust_model_graphite: /home/arsmith/colt/tables/graphite_dust.hdf5
dust_model_silicate: /home/arsmith/colt/tables/silicate_dust.hdf5
dust_model_PAH: /home/arsmith/colt/tables/PAH_dust.hdf5
f_PAH: 0.01                   # Fraction of carbonaceous dust in PAHs
j_exp: 0.75                   # Luminosity boosting exponent
# ion_max_eV: 100               # Maximum ionization threshold to include [eV]
metal_ions: true              # Include all metal ions
ion_bins: true                # Include all active ion bins
nu_exp: 2                     # Frequency boosting exponent
min_HI_bin_cdf: 0.8           # Minimum CDF value for >= 13.6 eV bins
max_bin_dex: 0.05             # Minimum frequency bin width in dex
# use_internal_energy: true     # Set temperature from the internal energy

n_photons: 100000000          # Number of photon packets (10^8)
max_iter: 20                  # Maximum number of iterations
max_error: 0.001              # Relative error for convergence

# Thermal solutions
output_cooling: true          # Output radiative cooling rates
output_heating: true          # Output radiative cooling rates
output_dT_dt: true            # Output cooling times
use_temperature_equilibrium: true  # Use temperature equilibrium
# max_cooling_time_yr: 1000000.   # Limit temperature equilibrium
courant_limited_cooling: true  # Courant limited cooling
use_internal_energy: false     # Use internal energy
T_rtol: 0.001
T_stab_factor: 1.1 
T_floor: 300

# Information about escape
output_photons: false         # Output escaped photon packets
#photon_file: photons          # Output a separate photon file
output_abundances: true       # Output abundances (x_HI etc)
output_photoheating: true     # Output photoheating rates
# photoheating_file: photoheating # Output a separate photoheating file
#spherical_escape: true        # Photons escape from a sphere
#escape_radius_bbox: 0.9       # Escape radius relative to the bbox
#emission_radius_bbox: 0.75    # Emission radius relative to the bbox

# UVB_model: FG11               # UV background (Faucher-Giguere 2011 model)
# self_shielding: true          # Self-shielding (Rahmati 2012 model)

# verbose: true                 # Verbose output for tests and debugging

