# COLT config filef
--- !projections              # Ray-based projections module

init_dir: ics                 # Initial conditions directory (default: "ics")
init_base: colt               # Initial conditions base name (optional)
output_dir: output            # Output directory name (default: "output")
output_base: halo_proj_RHD    # Output file base name (default: "colt")

# Information about sources
group_base: halo              # Group catalog base name (default: init_base)
select_group: true            # Specified halo is a group
use_all_groups: true          # Use all groups in the catalog file
use_group_catalog: true       # Use group catalog file
avoid_edges: false            # Avoid ray-tracing through edge cells
field_weight_pairs:           # Projection field-weight pairs
  - [rho, avg]
# - [rho2, avg]
# - [SFR, sum]
# - [T, mass]
# - [T_dust, mass]
  - [x_HI, mass]
# - [Z, mass]
# - [D, mass]
# - [v2, mass]
# - [v2_LOS, mass]
# - [v_LOS, mass]
# - [v_x, mass]
# - [v_y, mass]

# Information about cameras
image_radius_Rvir: 1          # Image radius relative to the bbox (1 Rvir)
# n_pixels: 128                 # Number of image pixels
# n_pixels: 512                 # Number of image pixels
pixel_width_pc: 100           # Pixel width in parsecs
poly_cameras: tetrahedron     # Polygon-based camera configuration
# n_side: 1                     # Healpix resolution for cameras
# cameras:                      # Add camera directions manually
#   - [0,0,1]
# verbose: true                 # Verbose output for tests and debugging

