# COLT config file
--- !ionization               # MCRT ionization equilibrium module

init_dir: ics                 # Initial conditions directory (default: "ics")
init_base: colt               # Initial conditions base name (optional)
output_dir: output            # Output directory name (default: "output")
output_base: M1500            # Output file base name (default: "colt")
abundances_base: states       # Output a separate abundances file

# Information about sources
source_file_Z_age: /home/arsmith/colt/tables/bpass-spectra-bin-imf_chab100.hdf5
dust_model: /home/arsmith/colt/tables/Draine-SMC.hdf5
# source_model: BPASS-CHAB-100  # Spectral source model
# dust_model: SMC               # Dust model: SMC, MW, etc.
j_exp: 0.75                   # Luminosity boosting exponent
# ion_max_eV: 100               # Maximum ionization threshold to include [eV]
metal_ions: true              # Include all metal ions
#ion_bins: true                # Include all active ion bins
HI_bin: false                 # Turn off HI
HeI_bin: false                # Turn off HeI
HeII_bin: false               # Turn off HeII
min_bin_angstrom: 1525        # Lowest energy bin edge [angstrom]
max_bin_angstrom: 1475        # Highest energy bin edge [angstrom]

n_photons: 100000000          # Number of photon packets (10^8)
max_iter: 1                   # Maximum number of iterations
max_error: 0.001              # Relative error for convergence

# Information about escape
output_photons: false         # Output escaped photon packets
# photon_file: photons          # Output a separate photon file
output_abundances: false      # Output abundances (x_HI etc)
# output_photoionization: true  # Output photoionization rates
# output_photoheating: true     # Output photoheating rates
# photoheating_file: photoheating # Output a separate photoheating file
spherical_escape: true        # Photons escape from a sphere
escape_radius_bbox: 0.9       # Escape radius relative to the bbox
emission_radius_bbox: 0.75    # Emission radius relative to the bbox

# Information about cameras
image_radius_bbox: 0.5        # Image radius relative to the bbox (1 Rvir)
n_pixels: 512                 # Number of image pixels
# n_exp: 0                      # Camera healpix directions exponent
cameras:                      # Add camera directions manually
  - [0,0,1]
  - [0,0,-1]
  - [0,1,0]
  - [0,-1,0]
  - [1,0,0]
  - [-1,0,0]

output_escape_fractions: true # Output camera escape fractions
# output_bin_escape_fractions: true # Output bin escape fractions
output_images: true           # Output surface brightness images
# output_bin_images: true       # Output bin SB images
output_mcrt_emission: true    # Output intrinsic emission without transport (mcrt)
# output_mcrt_attenuation: true # Output attenuated emission without scattering (mcrt)

UVB_model: FG11               # UV background (Faucher-Giguere 2011 model)
self_shielding: true          # Self-shielding (Rahmati 2012 model)
# read_molecular_fraction: true # Read x_H2 from the input file

#output_ion_age_freq_gas: true        # Activate gas flag
#output_ion_age_freq_dust: true       # Activate dust flag
#output_ion_age_freq_hydrogen: true   # Activate hydrogen flag
#output_ion_age_freq_oxygen: true     # Activate oxygen flag
# NO! # output_ion_age_freq: true            # Activates all relevant output flags

# cell_age_freq:                # Parameters for cell_age_freq output
#   age_edges_Myr: [0, 10, 100, 2000, 1e5] # Stellar age bin edges [Myr]
#   freq_edge_names: [SI, HI, HeI, HeII, max] # Coarse frequency bin edge names
#   # age_edges_Myr: [0, 1, 10, 100, 250, 500, 750, 2000, 1e5] # Stellar age bin edges [Myr]
#   # freq_edge_names: [SI, HI, NI, SII, HeI, NII, OII, OIII, max] # Coarse frequency bin edge names

# radial_age_freq:              # Parameters for radial_age_freq output
#   # radial_linspace_pc: [0, 1e4, 10] # Linearly spaced radial bins [pc]
#   radial_logspace_pc: [0, 5, 50] # Logarithmically spaced radial bins [pc]
#   # radial_edges_pc: [0, 1, 10, 100, 1e3] # Radial bin edges [pc]
#   age_edges_Myr: [0, 1, 10, 100, 250, 500, 750, 2000, 1e5] # Stellar age bin edges [Myr]
#   freq_edge_names: [SI, HI, NI, SII, HeI, NII, OII, OIII, max] # Coarse frequency bin edge names

# distance_age_freq:            # Parameters for distance_age_freq output
#   # distance_linspace_pc: [0, 1e4, 10] # Linearly spaced distance bins [pc]
#   distance_logspace_pc: [0, 5, 50] # Logarithmically spaced distance bins [pc]
#   # distance_edges_pc: [0, 1, 10, 100, 1e3] # Distance bin edges [pc]
#   age_edges_Myr: [0, 1, 10, 100, 250, 500, 750, 2000, 1e5] # Stellar age bin edges [Myr]
#   freq_edge_names: [SI, HI, NI, SII, HeI, NII, OII, OIII, max] # Coarse frequency bin edge names

# verbose: true                 # Verbose output for tests and debugging

