# COLT config file
--- !ionization               # MCRT ionization equilibrium module

init_dir: ics                 # Initial conditions directory (default: "ics")
init_base: colt               # Initial conditions base name (optional)
output_dir: output            # Output directory name (default: "output")
output_base: ion-eq-RHD       # Output file base name (default: "colt")
#abundances_base: states       # Output a separate abundances file

# Information about sources
source_file_Z_age: /home/arsmith/colt/tables/bpass-spectra-bin-imf_chab100.hdf5
dust_model: /home/arsmith/colt/tables/Draine-SMC.hdf5
j_exp: 0.75                   # Luminosity boosting exponent
metal_ions: false             # Include all metal ions
helium_ions: true             # Include all helium ions
ion_bins: true                # Include all active ion bins
#nu_exp: 2                     # Frequency boosting exponent
#min_HI_bin_cdf: 0.8           # Minimum CDF value for >= 13.6 eV bins
max_bin_dex: 0.05             # Minimum frequency bin width in dex
# use_internal_energy: true     # Set temperature from the internal energy

n_photons: 100000000          # Number of photon packets (10^8)
max_iter: 1                   # Maximum number of iterations
max_error: 0.001              # Relative error for convergence

# Information about escape
output_photons: false         # Output escaped photon packets
# photon_file: photons          # Output a separate photon file
output_abundances: false      # Output abundances (x_HI etc)
# output_photoionization: true  # Output photoionization rates
output_photoheating: false    # Output photoheating rates
# photoheating_file: photoheating # Output a separate photoheating file
spherical_escape: true        # Photons escape from a sphere
escape_radius_bbox: 0.5       # Escape radius relative to the bbox
emission_radius_bbox: 0.5     # Emission radius relative to the bbox

#output_escape_fractions: false # Output camera escape fractions
#output_bin_escape_fractions: false # Output bin escape fractions
#output_images: false           # Output surface brightness images
#output_bin_images: false       # Output bin SB images

# verbose: true                 # Verbose output for tests and debugging

