# COLT config file
--- !projections              # Ray-based projections module

init_dir: ics_tree            # Initial conditions directory (default: "ics")
init_base: colt               # Initial conditions base name (optional)
output_dir: output_tree       # Output directory name (default: "output")
output_base: proj_rho         # Output file base name (default: "colt")

# Information on simulation
cosmological: true            # Indicates whether the simulation is cosmological
perspective: true             # Perspective camera projections
stepback_factor: 0.5          # Perspective stepback factor (relative to radius)
override_volume: true         # Override projection volume normalization
avoid_edges: false            # Avoid ray-tracing through edge cells
# adaptive: true                # Adaptive convergence projections
# pixel_rtol: 1e-3              # Relative tolerence per pixel

# Information about fields
field_weight_pairs:
  - [rho, avg]
  - [rho2, avg]

# Information about Fade
#fade_in_length_bbox: 1        # Fade in length relative to the bbox
#fade_in_length_bbox: 0.4     # Fade in length relative to the bbox
fade_in_length_bbox: 0        # Fade in length relative to the bbox
#fade_in_width_bbox: 0.25      # Fade in width relative to the bbox
fade_in_width_bbox: 0.25      # Fade in width relative to the bbox
fade_out_length_bbox: 1       # Fade in length relative to the bbox
fade_out_width_bbox: 0.25     # Fade in width relative to the bbox

# Image information
#image_radius_bbox: 1          # Image radius relative to the bbox
#image_radius_bbox: 0.25       # Image radius relative to the bbox
image_radii_bbox: [0.45,0.25] # Image radius relative to the bbox
proj_radius_bbox: 0.6         # Projection depth relative to the bbox
#image_radius_bbox: 4.         # Image radius relative to the bbox
#proj_radius_bbox: 16.         # Projection depth relative to the bbox
proj_sphere: true             # Project through a spherical volume
# nx_pixels: 1280                 #Number of image pixels
# ny_pixels: 720
nx_pixels: 3840               # Number of image pixels
ny_pixels: 2160
# nx_pixels: 640                 #Number of image pixels
# ny_pixels: 360
# n_pixels: 3840                # Number of image pixels
#n_pixels: 1280                # Number of image pixels
#n_pixels: 2160                # Number of image pixels

# Camera information
camera_north: [0,0,1]         # Camera north orientation
# camera_north: [0,0,0]         # Camera north orientation
# n_rot: 360                    # Add camera directions manually
# phi_start: 0                  # Starting azimuthal angle [deg]
# phi_end: 360                  # Ending azimuthal angle [deg]
n_rot: 4                      # Add camera directions manually
phi_start: 0                  # Starting azimuthal angle [deg]
phi_end: 4                    # Ending azimuthal angle [deg]
rotate_with_snaps: true       # Flag to offset rotations by the snapshot number
rotation_axis: [0,0,1]

# verbose: true                 # Verbose output for tests and debugging
