# COLT config file
--- !ionization               # MCRT ionization equilibrium module

init_dir: ics_tree            # Initial conditions directory (default: "ics")
init_base: colt               # Initial conditions base name (optional)
output_dir: output_tree       # Output directory name (default: "output")
# output_dir: output_fdust_10 # Output directory name (default: "output")
# f_dust: 0.1                 # Fraction of metals locked in dust grains
# output_dir: output_fdust_20 # Output directory name (default: "output")
# f_dust: 0.2                 # Fraction of metals locked in dust grains
# output_dir: output_fdust_40 # Output directory name (default: "output")
# f_dust: 0.4                 # Fraction of metals locked in dust grains
output_base: M1500            # Output file base name (default: "colt")
# abundances_base: states     # Output a separate abundances file

output_stars: true            # Output star emission and escape
output_ion_stats_dust: true   # Ionization statistics for dust
output_ion_stats_gas: true    # Ionization statistics for gas

# # Group information
# focus_groups_on_emission: true # Center of luminosity position and velocity
# # output_map_groups: true       # Output escape fraction maps
# output_map2_groups: true      # Output escape fraction maps (and statistics)
# n_side_groups: 5              # Healpix resolution for group maps
# # output_radial_map_groups: true # Output radial surface brightness group maps
# # n_side_radial_groups: 3       # Healpix resolution for group radial maps
# # map_radius_kpc_groups: 500    # Radial group maps radius [kpc]
# # min_map_radius_pc_groups: 0.5 # Minimum radial distance for group maps [pc]
# # n_map_pixels_groups: 120      # Number of radial pixels for group radial maps
# output_radial_avg_groups: true # Output angle-averaged radial surface brightness
# radius_kpc_groups: 500        # Radial group avgs radius [kpc]
# min_radius_pc_groups: 0.5     # Minimum radial distance for group avgs [pc]
# n_pixels_groups: 120          # Number of radial pixels for group radial avgs
# group_flows:                  # Group flow statistics
#   radial_logspace_Rvir: [-3, 1, 41] # Logarithmically spaced radial bins [Rvir]
#   freq_edge_names: [min, max] # Coarse frequency bin edge names

# n_exp_map: 3                  # Healpix exponent for the line-of-sight map
# map_pixel_arcsec: 0.05        # Pixel size for line-of-sight map [arcsec]
output_map: true              # Output escape fraction maps
output_map2: true             # Output escape fraction maps (and statistics)
n_side_map: 10                # Healpix resolution for maps (try 10 later)
output_radial_map: true       # Output radial surface brightness maps
n_side_radial: 5              # Healpix resolution for radial maps (try 5 later)
map_radius_bbox: 0.75         # Radial maps radius [bounding box]
# output_bin_radial_map: true   # Output a line-of-sight healpix map of radial spectral data cubes
# min_map_radius_pc: 0.5        # Minimum radial distance for maps [pc]
n_map_pixels: 120             # Number of radial pixels for radial maps
output_radial_avg: true       # Output angle-averaged radial surface brightness
# radius_kpc: 500               # Radial avgs radius [kpc]
# min_radius_pc: 0.5            # Minimum radial distance for avgs [pc]
# n_radial_pixels: 120          # Number of radial pixels for radial avgs
radial_flow:                  # Radial flow statistics
  radial_logspace_pc: [0, 5, 51] # Logarithmically spaced radial bins [pc]
  freq_edge_names: [min, max] # Coarse frequency bin edge names

# focus_radial_on_emission: true
# shift_radial_on_emission: true

# Information about sources
cosmological: true            # Indicates whether the simulation is cosmological
source_file_Z_age: /home/arsmith/colt/tables/bpass-spectra-bin-imf_chab100.hdf5
#dust_model: /home/arsmith/colt/tables/SMC_WeingartnerDraine.hdf5
#dust_model: /home/arsmith/colt/tables/Draine-SMC-1e5.hdf5
dust_model_graphite: /home/arsmith/colt/tables/graphite_dust.hdf5
dust_model_silicate: /home/arsmith/colt/tables/silicate_dust.hdf5
dust_model_PAH: /home/arsmith/colt/tables/PAH_dust.hdf5
f_PAH: 0.01                   # Fraction of carbonaceous dust in PAHs
j_exp: 0.75                   # Luminosity boosting exponent
metal_ions: false             # Include all metal ions
helium_ions: false            # Include all helium ions
HI_bin: false                 # Turn off HI
HeI_bin: false                # Turn off HeI
HeII_bin: false               # Turn off HeII
min_bin_angstrom: 1525        # Lowest energy bin edge [angstrom]
max_bin_angstrom: 1475        # Highest energy bin edge [angstrom]
# max_streaming_kpc: 50         # Maximum free-streaming distance [kpc]

# n_photons: 1000000            # Number of photon packets (10^6)
n_photons: 10000000           # Number of photon packets (10^7)
# n_photons: 100000000          # Number of photon packets (10^8)
# n_photons: 1000000000         # Number of photon packets (10^9)
max_iter: 1                   # Maximum number of iterations
max_error: 0.001              # Relative error for convergence

# Information about escape
output_photons: false         # Output escaped photon packets
# photon_file: photons          # Output a separate photon file
output_abundances: false      # Output abundances (x_HI etc)
# output_photoionization: true  # Output photoionization rates
output_photoheating: false    # Output photoheating rates
# photoheating_file: photoheating # Output a separate photoheating file
spherical_escape: true        # Photons escape from a sphere
escape_radius_bbox: 0.75      # Escape radius relative to the bbox
emission_radius_bbox: 0.5     # Emission radius relative to the bbox

# Information about cameras
image_radius_bbox: 0.25       # Image radius relative to the bbox (1 Rvir)
n_pixels: 512                 # Number of image pixels
radial_image_radius_bbox: 0.5 # Radial image radius relative to the bbox (2 Rvir)
n_radial_pixels: 512          # Number of radial image pixels
poly_cameras: tetrahedron     # Polygon-based camera configuration

output_escape_fractions: true # Output camera escape fractions
output_bin_escape_fractions: true # Output bin escape fractions
output_images: true           # Output surface brightness images
output_bin_images: true       # Output bin SB images
output_radial_images: true    # Output radial surface brightness images
output_bin_radial_images: true  #Output bin radial surface brightness images.
output_mcrt_emission: true     # Output intrinsic emission without transport based on MCRT sampling
# output_mcrt_attenuation: true   # Output attenuated emission without scattering based on MCRT sampling

#verbose: true                 # Verbose output for tests and debugging
