# COLT config file
--- !ionization               # MCRT ionization equilibrium module

init_dir: ics_tree              # Initial conditions directory (default: "ics")
init_base: colt                 # Initial conditions base name (optional)
output_dir: output_tree         # Output directory name (default: "output")
# output_dir: output_fdust_10   # Output directory name (default: "output")
# f_dust: 0.1                   # Fraction of metals locked in dust grains
# output_dir: output_fdust_20   # Output directory name (default: "output")
# f_dust: 0.2                   # Fraction of metals locked in dust grains
# output_dir: output_fdust_40   # Output directory name (default: "output")
# f_dust: 0.4                   # Fraction of metals locked in dust grains
output_base: halo-M1500-RHD   # Output file base name (default: "colt")
# abundances_base: states       # Output a separate abundances file

output_stars: true            # Output star emission and escape
output_ion_stats_dust: true   # Ionization statistics for dust

# # Group information
# group_base: halo              # Group catalog base name (default: init_base)
# select_group: true            # Specified halo is a group
# use_all_groups: true          # Use all groups in the catalog file
# use_group_catalog: true       # Use group catalog file
# filter_group_catalog: true    # Filter group catalog file
# focus_groups_on_emission: true # Center of luminosity position and velocity
# # output_groups: true           # Output group statistics
# output_groups_obs: true       # Output group statistics for observations
# output_groups_vir: true       # Output group statistics for virial quantities
# output_groups_gal: true       # Output group statistics for galaxy quantities
# # output_map_groups: true       # Output escape fraction maps
# output_map2_groups: true      # Output escape fraction maps (and statistics)
# n_side_groups: 5              # Healpix resolution for group maps
# # output_radial_map_groups: true # Output radial surface brightness group maps
# # n_side_radial_groups: 3       # Healpix resolution for group radial maps
# # map_radius_kpc_groups: 500    # Radial group maps radius [kpc]
# # min_map_radius_pc_groups: 0.5 # Minimum radial distance for group maps [pc]
# # n_map_pixels_groups: 120      # Number of radial pixels for group radial maps
# output_radial_avg_groups: true # Output angle-averaged radial surface brightness
# radius_kpc_groups: 500        # Radial group avgs radius [kpc]
# min_radius_pc_groups: 0.5     # Minimum radial distance for group avgs [pc]
# n_pixels_groups: 120          # Number of radial pixels for group radial avgs
# group_flows:                  # Group flow statistics
#   radial_logspace_Rvir: [-3, 1, 41] # Logarithmically spaced radial bins [Rvir]
#   freq_edge_names: [min, max] # Coarse frequency bin edge names

# # Subhalo information
# subhalo_base: halo            # Subhalo catalog base name (default: init_base)
# # select_subhalo: true          # Specified halo is a subhalo
# use_all_subhalos: true        # Use all subhalos in the catalog file
# use_subhalo_catalog: true     # Use subhalo catalog file
# # filter_subhalo_catalog: true  # Filter subhalo catalog file
# focus_subhalos_on_emission: true # Center of luminosity position and velocity
# # output_subhalos: true         # Output subhalo statistics
# output_subhalos_obs: true     # Output subhalo statistics for observations
# output_subhalos_vir: true     # Output subhalo statistics for virial quantities
# output_subhalos_gal: true     # Output subhalo statistics for galaxy quantities
# # output_map_subhalos: true     # Output escape fraction maps
# output_map2_subhalos: true    # Output escape fraction maps (and statistics)
# n_side_subhalos: 5            # Healpix resolution for subhalo maps
# # output_radial_map_subhalos: true # Output radial surface brightness subhalo maps
# # n_side_radial_subhalos: 3     # Healpix resolution for subhalo radial maps
# # map_radius_kpc_subhalos: 500  # Radial subhalo maps radius [kpc]
# # min_map_radius_pc_subhalos: 0.5 # Minimum radial distance for subhalo maps [pc]
# # n_map_pixels_subhalos: 120    # Number of radial pixels for subhalo radial maps
# output_radial_avg_subhalos: true # Output angle-averaged radial surface brightness
# radius_kpc_subhalos: 500      # Radial subhalo avgs radius [kpc]
# min_radius_pc_subhalos: 0.5   # Minimum radial distance for subhalo avgs [pc]
# n_pixels_subhalos: 120        # Number of radial pixels for subhalo radial avgs
# subhalo_flows:                # Subhalo flow statistics
#   radial_logspace_Rvir: [-3, 1, 41] # Logarithmically spaced radial bins [Rvir]
#   freq_edge_names: [min, max] # Coarse frequency bin edge names

# focus_radial_on_emission: true
# shift_radial_on_emission: true

# Information about sources
cosmological: true            # Indicates whether the simulation is cosmological
source_file_Z_age: /home/arsmith/colt/tables/bpass-spectra-bin-imf_chab100.hdf5
#dust_model: /home/arsmith/colt/tables/SMC_WeingartnerDraine.hdf5
#dust_model: /home/arsmith/colt/tables/Draine-SMC-1e5.hdf5
dust_model_graphite: /home/arsmith/colt/tables/graphite_dust.hdf5
dust_model_silicate: /home/arsmith/colt/tables/silicate_dust.hdf5
dust_model_PAH: /home/arsmith/colt/tables/PAH_dust.hdf5
f_PAH: 0.01                   # Fraction of carbonaceous dust in PAHs
j_exp: 0.75                   # Luminosity boosting exponent
metal_ions: false             # Include all metal ions
helium_ions: false            # Include all helium ions
HI_bin: false                 # Turn off HI
HeI_bin: false                # Turn off HeI
HeII_bin: false               # Turn off HeII
min_bin_angstrom: 1525        # Lowest energy bin edge [angstrom]
max_bin_angstrom: 1475        # Highest energy bin edge [angstrom]
max_streaming_kpc: 50         # Maximum free-streaming distance [kpc]

# n_photons: 1000000            # Number of photon packets (10^6)
# n_photons: 10000000           # Number of photon packets (10^7)
# n_photons: 100000000          # Number of photon packets (10^8)
n_photons: 2000000000         # Number of photon packets (10^9)
max_iter: 1                   # Maximum number of iterations
max_error: 0.001              # Relative error for convergence

# Information about escape
output_photons: false         # Output escaped photon packets
# photon_file: photons          # Output a separate photon file
output_abundances: false      # Output abundances (x_HI etc)
# output_photoionization: true  # Output photoionization rates
output_photoheating: false    # Output photoheating rates
# photoheating_file: photoheating # Output a separate photoheating file
#spherical_escape: true        # Photons escape from a sphere
#escape_radius_Rvir: 1         # Escape radius relative to the virial radius
#emission_radius_Rvir: 1       # Emission radius relative to the virial radius

# Information about cameras
#image_radius_Rvir: 1          # Image radius relative to the virial radius
#n_pixels: 128                 # Number of image pixels
#cameras:                      # Add camera directions manually
#  - [0,0,1]

# output_escape_fractions: false # Output camera escape fractions
# output_bin_escape_fractions: false # Output bin escape fractions
# output_images: false           # Output surface brightness images
# output_bin_images: false       # Output bin SB images

#verbose: true                 # Verbose output for tests and debugging
